const COLOR_PRIMARY = "#ff0000";
const COLOR_SECONDARY = "#E7E7E7";
const COLOR_WHITE_PURE = "#ffffff";
const COLOR_WHITE = "#fafafa";
const COLOR_GRAY = "#ECECEC";
const COLOR_BLACK_TEXT_PRIMARY = "#212121";
const COLOR_BLACK_TEXT_SECONDARY = "#6e6e6e";

export {
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_BLACK_TEXT_PRIMARY,
  COLOR_BLACK_TEXT_SECONDARY,
  COLOR_WHITE,
  COLOR_WHITE_PURE,
  COLOR_GRAY,
};
